---
deployment:
  tasks:
    - export DEPLOYPATH=/home/viscctvc/repositories/vis

    - /usr/local/bin/php $DEPLOYPATH/artisan optimize:clear

    - /usr/local/bin/php $DEPLOYPATH/artisan config:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan route:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan view:cache

    - cp -r $DEPLOYPATH/storage/app/public/. /home/viscctvc/public_html/storage/
    - rm -rf /home/viscctvc/public_html/build/
    - cp -r $DEPLOYPATH/public/build/ /home/viscctvc/public_html/build/